### ISSUE TITLE
onDragEnd Event not updating Html Marker Position

### ISSUE THREAD

**Issue by adolfie450** [arnaudleclerc/AzureMapsControl.Components#24]
When the onDragEnd event fires, it is not possible to get the New location (Lat /Lng) of the HTML Marker

It returns the original location (starting location) of the Marker, even though the marker has been dragged on the Map.

any suggestions, thanks for the Great Application 

``
var marker = new AzureMapsControl.Components.Markers.HtmlMarker(

                        new AzureMapsControl.Components.Markers.HtmlMarkerOptions
                        {

                            Position = new AzureMapsControl.Components.Atlas.Position(MapLogitude, MapLatitude),

                            HtmlContent = "<b style='color:white'>" + location.Name + "</b><br /><img src = '/svg/location.png' />",

                            Draggable = true

                        },
                        AzureMapsControl.Components.Markers.HtmlMarkerEventActivationFlags.None().Enable(AzureMapsControl.Components.Markers.HtmlMarkerEventType.DragEnd));

                    marker.OnDragEnd += (args) =>
                    {
                       
                        /// Only returns starting cordinates before the Drag, not the Updated Coordinates. 
       
                        location.Longitude = args.HtmlMarker.Options.Position.Longitude;
                        location.Latitude =args.HtmlMarker.Options.Position.Latitude;

                    };

                    await eventArgs.Map.AddHtmlMarkersAsync(marker);
``

**Comment by arnaudleclerc** [comment]
Hi @adolfie450, thanks for opening this issue. You're right, the options of the updated marker are currently not serialized from the event. I'll need to rework a little bit how the options of the markers are serialized, but that should be quite straightforward. I'll try to take a look at it this weekend and will let you know.

**Comment by adolfie450** [comment]
Hi thanks for looking into this,

Map on click works, Ie if I click a on a position on a map, I can place a Marker, but not drag, or drag end. But then one is a MapEvent and the other is a Marker event.

Thanks for your efforts on this component, it really helps a lot.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by arnaudleclerc** [comment]
It should now be fixed on the v0.8.1. The options on the HtmlMarker should be updated whenever a marker event containing the options is received. 

I'll close this issue. Let me know if it works for you and feel free to reopen it if it is not the case

**Comment by adolfie450** [comment]
Thanks, It works 100% now, your Efforts are Greatly Appreciated !!!
