### ISSUE TITLE
Logging from map

### ISSUE THREAD

**Issue by Nickztar** [arnaudleclerc/AzureMapsControl.Components#32]
Currently using this and it's working well. One thing that annoys me a bit it the fact that there is so much log information being sent to console and hard to track other things. Logging is great during early stages but a way to turn it off would be really nice.

**Comment by arnaudleclerc** [comment]
As it uses the `ILogger` interface, you can tune the log level you want per namespace just by changing the configuration of your application (usually on `app.settings.json`). By default, it would log everything with is higher or equal to your default log level.

The following example would log everything from log level `Information` and higher coming from any namespace : 

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  }
}
```

You can completely deactivate the logging done by AzureMapsControl.Components like this : 

```
{
  "Logging": {
    "LogLevel": {
      "AzureMapsControl.Components": "None"
    }
  }
}
```

Let me know if this is what you needed!

**Comment by Nickztar** [comment]
This is exactly what I was after. Closing this then. Thanks for help!
