### ISSUE TITLE
x-ms-client-id is undefined when using anonymous authentication

### ISSUE THREAD

**Issue by philvessey** [arnaudleclerc/AzureMapsControl.Components#38]
**Describe the bug**
I have a valid access token from aad and I can see the token being passed in the Authorization header so the javascript function to get the token from my backend service is working. However as per https://docs.microsoft.com/en-us/azure/azure-maps/azure-maps-authentication there should also be x-ms-client-id in the header and that value should be the same as the configuration client id passed into the library configuration. However in the header, it is undefined.

<img width="232" alt="header" src="https://user-images.githubusercontent.com/814882/113507127-8ebb0980-9540-11eb-895e-22018e786d82.png">

This results in 401 unauthorised being returned from azure maps.

**Expected behavior**
x-ms-client-id should be set to the configuration client id passed into the library configuration.

**Comment by philvessey** [comment]
Tested in Postman with the token in the Authorization header and the clientid in x-ms-client-id and valid results are returned so everything configured correct in Azure. The library isn't populating x-ms-client-id which is the issue.

**Comment by arnaudleclerc** [comment]
Sounds right, I apparently forgot to affect it. I'll make a fix ASAP.

**Comment by philvessey** [comment]
Thanks, once updated ill test to make sure working as expected.

**Comment by arnaudleclerc** [comment]
@philvessey I have published a v `0.17.1-beta0001` where the `client id` should be part of the requests. Could you please check if it works for you ? If yes, I will publish later a 0.17.1

**Comment by philvessey** [comment]
Sure will have a look later on today.

**Comment by philvessey** [comment]
Working fine on 0.17.1-beta0001. Thanks for quick fix.

**Comment by arnaudleclerc** [comment]
Great, thanks for the feedback! I have now published a stable `0.17.1` containing the fix.
