### ISSUE TITLE
Geolocation Control

### ISSUE THREAD

**Issue by philvessey** [arnaudleclerc/AzureMapsControl.Components#39]
Hi

Is it possible to get this control added to the library?

https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/master/AzureMapsCodeSamples/Device%20Sensors/Geolocation%20control.html

Looks a simple control with a js script to get the users location and show an icon on the map. Sample is here:

https://azuremapscodesamples.azurewebsites.net/Device%20Sensors/Geolocation%20control.html

**Comment by arnaudleclerc** [comment]
Looks possible, as long as you include the js script to your application. This would be somehow similar to the overview or to the scale bar control. I'll try to take a look at it this week

**Comment by philvessey** [comment]
That's what I'm guessing - as long as the js is added like the overview control hopefully this can be added as a new control - would be ideal for the app I'm building if could.

**Comment by arnaudleclerc** [comment]
@philvessey This has been added on the v1.1.0. 

You can instantiate a `GeolocationControl` class and add it to the map like any other controls on the `AzureMap` element or by using `AddControlsAsync` on your instance of `Map`. It supports the two `GeolocationSuccess` and `GeolocationError` events. The `GetLastKnownPositionAsync` method returns a `Feature<Point>` with the last known location. You can also modify the options of the control using `SetOptionsAsync` and dispose it using `DisposeAsync`. The control will not be usable anymore after it has been disposed and the methods will throw a `ControlDisposedException` if they are called after disposal. Once disposed, the control is not part anymore of the `Controls` collection on the `Map`.

There is also a new `IGeolocationService` which allows you to check if the browser supports the geolocation by calling `IsGeolocationSupportedAsync`. You can inject it directly on your razor pages.

As explained before, you need to include the script tag on your application to make it work. You can find it on this Git repository : [https://github.com/Azure-Samples/azure-maps-geolocation-control](https://github.com/Azure-Samples/azure-maps-geolocation-control)

```
    <script src="~/azure-maps-geolocation-control.min.js"></script>
```

You can take a look at the documentation to find a working example [https://github.com/arnaudleclerc/AzureMapsControl.Components/tree/develop/docs/controls/geolocation](https://github.com/arnaudleclerc/AzureMapsControl.Components/tree/develop/docs/controls/geolocation)

I hope this fits. I will close this issue, but feel free to reopen it necessary 😊

**Comment by philvessey** [comment]
Looks good from a quick glance over the sample - I like that you have added a browser support check too.
