### ISSUE TITLE
Add support for Indoor Maps

### ISSUE THREAD

**Issue by alandillon** [arnaudleclerc/AzureMapsControl.Components#45]
How hard would it be to add support for indoor maps?

<script src="https://atlas.microsoft.com/sdk/javascript/indoor/0.1/atlas-indoor.min.js"></script>

**Comment by arnaudleclerc** [comment]
I didn't take a look at the code of the module yet, so I cannot exactly say what needs to be done, but based on what I saw on the documentation that looks possible. I can imagine a new IndoorManager class or service with a couple of new events, and a new level control.

I'll try to find some time next week to take a look at it and check exactly what needs to be done, but you can also give it a shot if you want to!

**Comment by arnaudleclerc** [comment]
I am currently working on it by reproducing this sample : https://docs.microsoft.com/en-us/azure/azure-maps/how-to-use-indoor-module

The methods on the `IndoorManager` and the events are still missing, but this would look like that : 

```
@page "/Indoor"

@using AzureMapsControl.Components.Map
@using Microsoft.Extensions.Configuration

@inject AzureMapsControl.Components.Indoor.IIndoorService IndoorService
@inject IConfiguration Configuration

<AzureMap Id="map"
          CameraOptions="new CameraOptions { Center= new AzureMapsControl.Components.Atlas.Position(-122.13315, 47.63637), Zoom = 19 }"
          StyleOptions="new StyleOptions { Style = MapStyle.Blank }" 
          EventActivationFlags="AzureMapsControl.Components.Map.MapEventActivationFlags.None().Enable(AzureMapsControl.Components.Map.MapEventType.Ready)"
          OnReady="OnMapReadyAsync"/>

@code {

    public async Task OnMapReadyAsync(MapEventArgs eventArgs)
    {
        var levelControl = new AzureMapsControl.Components.Indoor.LevelControl(new AzureMapsControl.Components.Indoor.LevelControlOptions {
            Position = AzureMapsControl.Components.Controls.ControlPosition.TopRight
        });

        var indoorManager = await IndoorService.CreateIndoorManagerAsync(
            new AzureMapsControl.Components.Indoor.IndoorManagerOptions {
                LevelControl = levelControl,
                StatesetId = Configuration["Indoor:StatesetId"],
                TilesetId = Configuration["Indoor:TilesetId"],
                Theme = AzureMapsControl.Components.Indoor.IndoorLayerTheme.Auto
            }
        );
    }

}
```

**Comment by arnaudleclerc** [comment]
Sorry for the delay, I did not have a lot of time to work on this lately, but I finally managed to publish a version 1.7.0 including the support of the indoor module. Take a look at the documentation : https://github.com/arnaudleclerc/AzureMapsControl.Components/tree/develop/docs/indoor.

I will close this issue, but feel free to reopen it if necessary!
