### ISSUE TITLE
adding a BubbleLayer raise a source "SOURCENAME" not found exception.

### ISSUE THREAD

**Issue by spicamelot** [arnaudleclerc/AzureMapsControl.Components#50]
**Describe the bug**

When adding a bubbleLayer to the map, an error is raised by atlas.js :

```
atlas.js:1601 Error: layers.bb5b1acf-d234-456a-88eb-cdfcf202abea: source "locationsDS" not found
    at Object.emitValidationErrors (atlas.js:10809)
    at emitValidationErrors (atlas.js:32822)
    at Style._validate (atlas.js:33847)
    at Style.addLayer (atlas.js:33335)
    at Map.addLayer (atlas.js:41190)
    at LayerManager._addMapboxLayers (atlas.js:76275)
    at LayerManager._addLayer (atlas.js:76239)
    at LayerManager.add (atlas.js:76182)
    at Function.Core.addLayer (azure-maps-control.js:235)
    at blazor.server.js:1
```

This does not happen all the time. From a vanilla project, this occurs one time out of ten. On a larger projet thats loads data and that manage on additional layer, it happens at least once in two. And for the larger project, when the error is raised, it is always raised twice (once for each layer)

Of course, the layer is not visible on the map.

**Step to reproduce**

From a vanilla Blazor Server web application, adding AzureMapsControl.Components 1.8.3, registering service and adding atlas js and css (not minified). Replace the content of Index.razor by this :

```
@page "/"
@using AzureMapsControl.Components.Data
@using AzureMapsControl.Components.Map
@using AzureMapsControl.Components.Markers
@using AzureMapsControl.Components.Atlas
<AzureMap Id="map"
          CameraOptions="cameraOptions"
          StyleOptions="StyleOptions"
          EventActivationFlags="MapEventActivationFlags
    .None()
    .Enable(MapEventType.Ready)"
          OnReady="OnMapReady" 
          />
@code {
    CameraOptions cameraOptions = null;
    public StyleOptions StyleOptions = null;

    private AzureMapsControl.Components.Data.DataSource dataSource { get; set; }
    private AzureMapsControl.Components.Layers.BubbleLayer clusterLayer { get; set; }

    protected override void OnInitialized()
    {
        StyleOptions = new StyleOptions
        {
            ShowLogo = false,
            ShowFeedbackLink = false,
            AutoResize = true,
            Language = "fr",
        };
        cameraOptions = new CameraOptions();
        cameraOptions.Center = new AzureMapsControl.Components.Atlas.Position(-9.152, 38.733);
        cameraOptions.Zoom = 11.2;
    }
    public async Task OnMapReady(MapEventArgs events)
    {
        const string dataSourceId = "locationsDS";
        dataSource = new AzureMapsControl.Components.Data.DataSource(dataSourceId);
        await events.Map.AddSourceAsync(dataSource);

        clusterLayer = new AzureMapsControl.Components.Layers.BubbleLayer
        {
            Options = new AzureMapsControl.Components.Layers.BubbleLayerOptions
            {
                Source = dataSourceId,
            }
        };
        await events.Map.AddLayerAsync(clusterLayer);
    }
}
```

I tried to debug atlas.js, and I can see the error occuring even if I manually wait some time between calls.
I tried to modify AzureMapControls.Components to add some dummy timeout await new Promise(f => setTimeout(f, 2000)); before addLayer method, and in my code, just after AddSourceAsync 

**Expected behavior**
For the vanilla project, the map should be loaded without error in the browser console
For larger project, the map should be loadad without error, and the layer should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/67462386/126773706-4713c8aa-6840-424b-9995-c1e2cb2bb469.png)

That sounds as if a component was not yet registered when the error occurs, but I cannot find exactly what happens.

**Comment by arnaudleclerc** [comment]
I have no idea what's wrong right now, all looks fine, but I have the impression that the data source was not added correctly. 

I am currently away until beginning of August and I won't be able to look at it until then. I'll try to investigate more when I come back. I'll mark that as a bug in the meantime.

But as usual, if you find the reason and want to fix it, feel free to open a PR. I'm still able to review them 😊

**Comment by spicamelot** [comment]
I am still investigating. That is not specific to Bubble Layer.

On my application, i replaced the datasource and the layers by the code you have provided for the symbol layer sample.
On the first run, the sample was fine. After the first refresh of the page, an error occured for one of the layer (as you can see below).

![image](https://user-images.githubusercontent.com/67462386/126965407-75275f05-66df-44e7-b75d-984b52eca8e1.png)

I have tried to run the code outside my corporate network to be sure (hosting on Azure, an using my phone as client), but issue remains. I will check my initialization, there is obviously someting that goes wrong on my code, otherwise other people should face the same issue.

**Comment by IVData** [comment]
@spicamelot I've just started having the same issue on a page that has been working for a few weeks beforehand.

The fact that it was previously working is probably a big clue - looking at my page source the atlas lib comes straight from Microsoft: `<script src="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js"></script>` so perhaps they've changed something.

**Comment by spicamelot** [comment]
I was notre having this issue before. And maybe you are right with Atlas.js reference. I tried to change to 2.1 version of atlas.js, but the issue remains. 

I am facing this issue far more often from my working laptop on my corporate development environment (with debug) than with my mobile phone with an azure hosted app with Internet direct access. 

It occurs at least with bubble layer and symbol layer.

**Comment by IVData** [comment]
Where are you seeing version numbers for atlas.js? 

The version I've switched to is here, interested to see if it works for you: https://web.archive.org/web/20210430090243/https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js

**Comment by spicamelot** [comment]
Thanks.
I switched to a local atlas.min.js based on the archive.org version.

But the error remains

[image: image.png]

To answer your question about version number : I guess that the number in
the URL is a version number.

For exemple :

https://atlas.microsoft.com/sdk/javascript/mapcontrol/*2*/atlas.min.js
https://atlas.microsoft.com/sdk/javascript/drawing/*0.1*/atlas-drawing.min.js
So, I tried with 2.1 :
https://atlas.microsoft.com/sdk/javascript/mapcontrol/*2.1*/atlas.min.js
but I don't even check if the content was the same.

**Comment by arnaudleclerc** [comment]
Thank you for looking into that folks, that's really helpful! There was indeed a new release of the atlas library (version 2.1) a month ago, but I cannot find any changelog anywhere 

![image](https://user-images.githubusercontent.com/9578038/127807777-98325227-a67f-486f-a2da-bd3d8d582047.png)

By comparing the v2.0 and v2.1 manually, I can see there is a new `validateLayer` method which checks if the source exists on `options.style.sources`. This property is unknown to me, but I guess it is set by the atlas library itself. I will have to debug it to check what needs to be done to support the v2.1.

In the meantime, you can still target the v2.0 of the atlas library by referencing https://atlas.microsoft.com/sdk/javascript/mapcontrol/2.0/atlas.js. Targeting only https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.js seems to target the highest 2.x version.

**Comment by arnaudleclerc** [comment]
I don't really understand why it is happening, it seems to be a race condition between adding the datasource and adding the layer. Sometimes it works, sometimes it does not. And I don't think I can influence it, so I guess we need to add the layer differently. 

A solution which does make sense would be to add the layer once the `datasourceadded` event is received. For the BubbleLayer sample, that would mean something like that : 

```
@page "/Layers/BubbleLayerOnReady"

@using AzureMapsControl.Components.Map
<AzureMap Id="map"
          CameraOptions="new CameraOptions { Zoom = 2 }"
          EventActivationFlags="MapEventActivationFlags
                                .None()
                                .Enable(MapEventType.Ready, MapEventType.SourceAdded)"
          OnReady="OnMapReady"
          OnSourceAdded="OnDatasourceAdded" />

@code  {

    private readonly string _datasourceId = "bubbleDataSource";

    public async Task OnMapReady(MapEventArgs eventArgs)
    {
        var dataSource = new AzureMapsControl.Components.Data.DataSource(_datasourceId)
        {
            EventActivationFlags = Components.Data.DataSourceEventActivationFlags.None()
        };
        await eventArgs.Map.AddSourceAsync(dataSource);

        var json = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"57fd117c-abac-4985-9ead-36168c0e359e\"},\"id\":\"57fd117c-abac-4985-9ead-36168c0e359e\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[0,0]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"01ebb77e-18e6-4dfa-8c77-db3c4fd7408a\"},\"id\":\"01ebb77e-18e6-4dfa-8c77-db3c4fd7408a\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[5,5]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"a388ff48-c5f4-4cb5-a9ab-604ae08c1564\"},\"id\":\"a388ff48-c5f4-4cb5-a9ab-604ae08c1564\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10,10]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"12b2f8f9-47bf-4c90-92ac-e82fb5e8f64b\"},\"id\":\"12b2f8f9-47bf-4c90-92ac-e82fb5e8f64b\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15,15]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"19c81734-50d5-4d23-b57d-58d3da7746e2\"},\"id\":\"19c81734-50d5-4d23-b57d-58d3da7746e2\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[20,20]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"88852e6d-b105-483e-a88a-98ec536b10ca\"},\"id\":\"88852e6d-b105-483e-a88a-98ec536b10ca\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[25,25]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"c8bec3fb-e6ea-4297-b386-c328d277639c\"},\"id\":\"c8bec3fb-e6ea-4297-b386-c328d277639c\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[30,30]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"591fab80-bc14-4efd-b20d-5be29cf9769d\"},\"id\":\"591fab80-bc14-4efd-b20d-5be29cf9769d\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[35,35]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"0bdcddbd-c895-4356-b3b3-c3330003b28c\"},\"id\":\"0bdcddbd-c895-4356-b3b3-c3330003b28c\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[40,40]}},{\"type\":\"Feature\",\"properties\":{\"_azureMapsShapeId\":\"e63f463b-3605-4847-8ea3-2948187f601d\"},\"id\":\"e63f463b-3605-4847-8ea3-2948187f601d\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[45,45]}}]}";
        await dataSource.AddAsync(System.Text.Json.JsonDocument.Parse(json));
    }

    public async Task OnDatasourceAdded(MapSourceEventArgs eventArgs)
    {
        if (eventArgs.Source.Id == _datasourceId)
        {
            var layer = new AzureMapsControl.Components.Layers.BubbleLayer
            {
                Options = new Components.Layers.BubbleLayerOptions
                {
                    Color = new Components.Atlas.ExpressionOrString("white"),
                    Radius = new Components.Atlas.ExpressionOrNumber(5),
                    StrokeColor = new Components.Atlas.ExpressionOrString("#4288f7"),
                    StrokeWidth = new Components.Atlas.ExpressionOrNumber(6),
                    Source = _datasourceId
                },
                EventActivationFlags = Components.Layers.LayerEventActivationFlags.None().Enable(Components.Layers.LayerEventType.MouseEnter, Components.Layers.LayerEventType.MouseLeave)
            };

            layer.OnMouseEnter += async _ =>
            {
                await eventArgs.Map.SetCanvasContainerStylePropertiesAsync(new Dictionary<string, string> {
        { "cursor", "pointer" }
            });
            };

            layer.OnMouseLeave += async _ =>
            {
                await eventArgs.Map.SetCanvasContainerStylePropertiesAsync(new Dictionary<string, string> {
        { "cursor", "grab" }
            });
            };

            await eventArgs.Map.AddLayerAsync(layer);
        }
    }
}
```

Would that be a valid solution for you ?

I personally like this approach and I would make it a general advice to add a datasource this way, because it is the only way I can guarantee that the datasource has been added before adding a layer. 

I will have to push a new version for that though because I forgot to bind the `sourceadded` and `sourceremoved` events, even if the signature is already there. I will let you know when this is available.

**Comment by spicamelot** [comment]
I will try this soon (I am away now 🙂). But I had try this, and yes, I guessed that the data source event was not enabled :)

**Comment by arnaudleclerc** [comment]
The `sourceadded` and `sourceremoved` events have been added in the 1.9.0. Let me know if it works when you can try it out 😊

**Comment by arnaudleclerc** [comment]
@spicamelot I will close this as it seems fixed to me. Feel free to try it out whenever you have time and give me feedback. You can of course reopen this issue if you still face it :)
