### ISSUE TITLE
What is the token that must be specified there?

### ISSUE THREAD

**Issue by borisgr04** [arnaudleclerc/AzureMapsControl.Components#53]
Question:
What is the token that must be specified in url_of_my_token_endpoint?

` 
azureMapsControl.Extensions.getTokenCallback = (resolve, reject, map) => {
            const url = "url_of_my_token_endpoint";
            fetch(url).then(function (response) {
                return response.text();
            }).then(function (token) {
                resolve(token);
            });
        };`

**Comment by arnaudleclerc** [comment]
This is the URI to call to get a token for Azure maps in case you want to use the anonymous authentication. That would usually be an API you host yourself and which creates a valid token for your Azure Maps account.

**Comment by arnaudleclerc** [comment]
I will close this issue, as this was more a question. If you need more information, feel free to reopen it.
