### ISSUE TITLE
Error: Microsoft.JSInterop.JSException: Could not find 'azureMapsControl.Core.addMap' ('azureMapsControl' was undefined).

### ISSUE THREAD

**Issue by ADefWebserver** [arnaudleclerc/AzureMapsControl.Components#58]
When I try to run I get Error: 
`Microsoft.JSInterop.JSException: Could not find 'azureMapsControl.Core.addMap' ('azureMapsControl' was undefined).`

**To Reproduce**
1) Open the AzureMapsControl.Sample project in Visual Studio 2022 and put in Key in appsettings,json like this:

`{
  "AzureMaps": {
    "SubscriptionKey": "{{my Key}}"
  },`

2) Add the AzureMapsControl.Components so it builds
3) Run it

![image](https://user-images.githubusercontent.com/1857799/152265136-eec01837-7c81-4523-b066-b40aee112dc8.png)

**Comment by ADefWebserver** [comment]
It does work if I only run the AzureMapsControl.Sample project in Visual Studio 2022 (using "Start Without Debugging" because "Start Debugging" only opens a blank web page) and add the [Nuget](https://www.nuget.org/packages/AzureMapsControl.Components/) package to it.

**Comment by arnaudleclerc** [comment]
You need to transpile the typescript code to create the .js files, which is not done via the build of the projects. For that, under `/src/AzureMapsControl.Components`, simply run `npm run build`. 

Let me know if this worked!

**Comment by ADefWebserver** [comment]
Thank you for the explanation on how to compile the source code. Since simply adding the NuGet package has it working I am good to go. The reason I don't want to use the NPM method is I have several Angular projects that have not been upgraded and I can't upgrade my NPM (sigh)
