### ISSUE TITLE
Feature deserialization on drawing events

### ISSUE THREAD

**Issue by miguelhasse** [arnaudleclerc/AzureMapsControl.Components#66]
Feature deserialization throws an exception for all drawing events apart from 'DrawingModeChanged' and 'DrawingStarted'.
Also, actual Geometry data will never get deserialized in current implementation.

`Error: System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'AzureMapsControl.Components.Atlas.Feature'.`

**Comment by miguelhasse** [comment]
@arnaudleclerc it certainly seems to be the same as [#68](https://github.com/arnaudleclerc/AzureMapsControl.Components/issues/68). I'll give it a try, and post results here.

**Comment by arnaudleclerc** [comment]
I published a v1.12.0 a couple of days ago where this issue should be fixed. I will close this issue, but feel free to reopen it if the problem persists.
