### ISSUE TITLE
Is creating branches turned off?

### ISSUE THREAD

**Issue by DavidThielen** [arnaudleclerc/AzureMapsControl.Components#89]
I created a couple of small changes to help people building the samples for the first time. I went to create a branch to push them up - and that seems to be unavailable.

Is there something I need to do first before pushing up some suggested changes?

thanks - dave

**Comment by arnaudleclerc** [comment]
Hi Dave. The usual way would be to fork this repository, create a branch on this fork and then create a pull request targeting the develop branch here. As far as I know, this should still work. Do you mind trying that out ? Let me know if it worked.

**Comment by DavidThielen** [comment]
Hi @arnaudleclerc - I looked at that, but didn't see the buttons to create a branch. Am I looking in the wrong place?

thanks - dave

<img width="983" alt="ForkBranch" src="https://github.com/arnaudleclerc/AzureMapsControl.Components/assets/52540224/66430798-bbe7-416e-b590-0a3e7e5fe177">

**Comment by rbrundritt** [comment]
The button is on the main page: 

![image](https://github.com/arnaudleclerc/AzureMapsControl.Components/assets/6459716/3d895003-3b6f-4793-8b8d-51f912270dcb)

**Comment by DavidThielen** [comment]
thanks - I've checked in my change. (Pretty minor but it will hopefully help others save &frac12; hour or so when they first use this.)
